### ISSUE TITLE
Happy to work on Colab Notebook

### ISSUE THREAD

**Issue by sayakpaul** [MediaTek-NeuroPilot/mai21-learned-smartphone-isp#1]
Hi folks.

Huge thanks for organizing this. I am a MobileML practitioner and have experience with many deep learning models that are mobile-friendly. Some projects:

* https://github.com/margaretmz/selfie2anime-e2e-tutorial
* https://github.com/margaretmz/Cartoonizer-with-TFLite
* https://github.com/margaretmz/segmentation-style-transfer
* https://github.com/sayakpaul/Adventures-in-TensorFlow-Lite

I wanted to know if you folks would be up if submitted a Colab Notebook showing the model conversion and inference process in TensorFlow Lite. This way I think the community will be able to play with the pre-trained models quickly.

**Comment by hsienkaikuo** [comment]
Hi sayakpaul,

Colab Notebook (for Model Conversion & Inference Process) is an interesting idea. We will take this into our consideration. Beside this Challenge, we do have some works using Python Notebooks which will be released sometime in 21’H1. Hope you will find that useful too.

**Comment by sayakpaul** [comment]
I have prepared the notebook. So, let me know if I should create a PR.

**Comment by hsienkaikuo** [comment]
This is awesome. Please go ahead create the PR. We will manage to merge it.
