### ISSUE TITLE
How was the validation data obtained?

### ISSUE THREAD

**Issue by sayakpaul** [MediaTek-NeuroPilot/mai21-learned-smartphone-isp#2]
Hi folks,

I am trying to get the provided code running. Wanted to know how was the validation split obtained? Was it obtained from the original training pairs (RAW-RGB)?

**Comment by cmhungsteve** [comment]
Yes, you can try cross-validation or any other splitting methods you want to obtain the validation split for this codebase.
The main purpose is to get the hyper-parameters for training the model.
