### ISSUE TITLE
Doubt regarding putting additional terms after tanh in the final layer

### ISSUE THREAD

**Issue by sayakpaul** [MediaTek-NeuroPilot/mai21-learned-smartphone-isp#6]
I wanted to know the rationale behind [adding additional terms after TanH](https://github.com/MediaTek-NeuroPilot/mai21-learned-smartphone-isp/blob/master/model.py#L72). Is it to scale back the pixel value range?

**Comment by cmhungsteve** [comment]
Yes.
We follow [PyNet](https://github.com/aiff22/PyNET) for this part.

**Comment by sayakpaul** [comment]
So, long story cut short it's there to scale back the values to [0, 1] range. Am I correct?

**Comment by cmhungsteve** [comment]
Yes, you're right.
